/**
 * EventHandler.java
 * 
 * Copyright (C) 2016 by Arménio Pinto
 * Please read the file LICENSE for the license details.
 */
package com.armeniopinto.stress.control;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Component;

/**
 * Handles the asynchronous events generated by the platform's components.
 * 
 * @author armenio.pinto
 */
@Component
public class EventHandler {

	private static final Logger LOGGER = LoggerFactory.getLogger(EventHandler.class);

	public void handle(final Event event) {
		LOGGER.info(String.format("XXX %s", event));
	}

}
