/**
 * Event.java
 * 
 * Copyright (C) 2016 by Arménio Pinto
 * Please read the file LICENSE for the license details.
 */
package com.armeniopinto.stress.control;

import java.util.Map;

/**
 * An asynchronous event generated by one of the platform's components.
 * 
 * @author armenio.pinto
 */
public class Event extends Message {

	public static final String MESSAGE_TYPE = "Event";

	public Event(final Map<String, Object> data) {
		super(MESSAGE_TYPE, data);
	}

}
